### ISSUE TITLE
p11-kit-0.23.10 fails to compile on Solaris 11.3 with GCC 4.9.4

### ISSUE THREAD

**Issue by joernclausen** [p11-glue/p11-kit#146]
When building p11-kit on Solaris 11.3/i86 using GCC 4.9.4, compilation fails with

  CC       common/lexer.lo
  CC       common/message.lo
In file included from /usr/include/sys/types.h:12:0,
                 from common/compat.h:40,
                 from common/message.c:46:
/opt/pkg-gcc/4.9.4/lib/gcc/i386-pc-solaris2.11/4.9.4/include-fixed/sys/feature_tests.h:367:2: error: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications         require the use of c99"
 #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications \
  ^
gmake[2]: *** [common/message.lo] Error 1

Passing '-std=c99' via CFLAGS results in

/opt/pkg-gcc/4.9.4/lib/gcc/i386-pc-solaris2.11/4.9.4/include-fixed/sys/feature_tests.h:363:2: error: #error "Compiler or options invalid for pre-UNIX 03 X/Open applications    and pre-2001 POSIX applications"
 #error "Compiler or options invalid for pre-UNIX 03 X/Open applications \

**Comment by nmav** [comment]
Not sure we can do something about it. The compiler fails on a basic operation such as using a system header.
